language: python

sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

python:
  - "2.7"
  - "pypy"

install:
  - pip install tox>=1.8

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')

notifications:
  email: false
